server:
  port: 8088
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: true
  redis:
    host: 120.25.166.243
    port: 6379
    password: 12345678
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

shiro:
  loginUrl: /sys/system/login
  unauthorizedUrl: /err
  successUrl: /success
  filterChainDefinitionList:
    - key: /logout
      value: logout
    - key: /index
      value: anon
    - key: /**
      value: authc

version: V1.0_20200108

logging:
  config: classpath:log4j2.yml